@php $value = fn ($field) => old($field, $plan?->{$field}); @endphp
@if($errors->any())<div class="alert alert-danger">@foreach($errors->all() as $error)<div>{{ $error }}</div>@endforeach</div>@endif
<form action="{{ $formAction }}" method="POST" enctype="multipart/form-data" class="main-footer">
    @csrf @if($formMethod !== 'POST') @method($formMethod) @endif
    <h2 class="text-center mb-5">{{ $formTitle }}</h2>
    <h4>Hero and Intro</h4>
    <input class="form-control mb-3" name="hero_kicker" placeholder="Find your fit" value="{{ $value('hero_kicker') }}"><input class="form-control mb-3" name="hero_title" placeholder="Pricing Table" value="{{ $value('hero_title') }}"><textarea class="form-control mb-3" name="hero_description" rows="2" placeholder="Hero description">{{ $value('hero_description') }}</textarea>
    <label class="form-label">Hero Image</label><input type="file" class="form-control mb-3" name="hero_image" accept="image/*">@if($plan?->hero_image)<img src="{{ asset('storage/' . $plan->hero_image) }}" alt="Hero" width="160" height="100" style="object-fit:cover" class="mb-4">@endif
    <input class="form-control mb-3" name="intro_kicker" placeholder="A plan for every point of view" value="{{ $value('intro_kicker') }}"><input class="form-control mb-3" name="intro_title" placeholder="Style support that works at your pace." value="{{ $value('intro_title') }}"><textarea class="form-control mb-3" name="intro_description" rows="3" placeholder="Intro description">{{ $value('intro_description') }}</textarea>
    <div class="row"><div class="col-md-4"><input class="form-control mb-4" name="monthly_label" placeholder="Monthly" value="{{ $value('monthly_label') }}"></div><div class="col-md-4"><input class="form-control mb-4" name="yearly_label" placeholder="Yearly" value="{{ $value('yearly_label') }}"></div><div class="col-md-4"><input class="form-control mb-4" name="yearly_badge" placeholder="Save 20%" value="{{ $value('yearly_badge') }}"></div></div>
    <h4>Plan</h4><input class="form-control mb-3" name="name" placeholder="Starter Plan" value="{{ $value('name') }}" required><div class="row"><div class="col-md-4"><input class="form-control mb-3" name="currency" placeholder="$" value="{{ $value('currency') }}"></div><div class="col-md-4"><input class="form-control mb-3" name="price" placeholder="19" value="{{ $value('price') }}" required></div><div class="col-md-4"><input class="form-control mb-3" name="period_label" placeholder="/Month" value="{{ $value('period_label') }}"></div></div><textarea class="form-control mb-3" name="description" rows="3" placeholder="Plan description">{{ $value('description') }}</textarea><div class="row"><div class="col-md-6"><input class="form-control mb-4" name="button_text" placeholder="Try For Free" value="{{ $value('button_text') }}"></div><div class="col-md-6"><input class="form-control mb-4" name="button_url" placeholder="/pages/contact-1" value="{{ $value('button_url') }}"></div></div>
    <h4>Features</h4><input class="form-control mb-3" name="feature_heading" placeholder="Key Features:" value="{{ $value('feature_heading') }}">
    @foreach(range(1, 5) as $number)<div class="row"><div class="col-md-9"><input class="form-control mb-3" name="feature_{{ $number }}_name" placeholder="Feature {{ $number }}" value="{{ $value('feature_'.$number.'_name') }}"></div><div class="col-md-3"><label class="form-check mt-2"><input class="form-check-input" type="checkbox" name="feature_{{ $number }}_included" value="1" {{ old('feature_'.$number.'_included', $plan?->{'feature_'.$number.'_included'} ?? false) ? 'checked' : '' }}> Included</label></div></div>@endforeach
    <h4>Bottom Note</h4><input class="form-control mb-3" name="note_title" placeholder="Not sure which plan is right for you?" value="{{ $value('note_title') }}"><input class="form-control mb-3" name="note_description" placeholder="Our style team can help you choose a starting point." value="{{ $value('note_description') }}"><div class="row"><div class="col-md-6"><input class="form-control mb-4" name="note_link_text" placeholder="Talk to an expert" value="{{ $value('note_link_text') }}"></div><div class="col-md-6"><input class="form-control mb-4" name="note_link_url" placeholder="/pages/contact-1" value="{{ $value('note_link_url') }}"></div></div>
    <label class="form-check mb-3"><input class="form-check-input" type="checkbox" name="popular" value="1" {{ old('popular', $plan?->popular ?? false) ? 'checked' : '' }}> Most popular</label><label class="form-check mb-4"><input class="form-check-input" type="checkbox" name="status" value="1" {{ old('status', $plan?->status ?? true) ? 'checked' : '' }}> Active</label><button type="submit" class="btn btn-primary">{{ $plan ? 'Update Pricing Plan' : 'Save Pricing Plan' }}</button>
</form>