@include('admin.header')
@include('admin.sidebar')
<div id="layoutSidenav"><div id="layoutSidenav_content"><div class="container-fluid px-4">
@if($errors->any())<div class="alert alert-danger">@foreach($errors->all() as $error)<div>{{ $error }}</div>@endforeach</div>@endif
<form action="{{ route('admin.promo-grid.update', $promoGrid) }}" class="promo-grid main-footer" method="POST" enctype="multipart/form-data">
@csrf @method('PUT')<h2 class="text-center mb-5">Edit Promo Grid</h2>
<h4>Large Banner Image</h4><img src="{{ str_starts_with($promoGrid->large_image, 'http') ? $promoGrid->large_image : asset('storage/' . $promoGrid->large_image) }}" width="180" height="120" style="object-fit:cover" class="mb-3"><input type="file" class="form-control mb-3" name="large_image"><input class="form-control mb-3" name="large_label" value="{{ old('large_label', $promoGrid->large_label) }}"><input class="form-control mb-4" name="large_link" value="{{ old('large_link', $promoGrid->large_link) }}">
<h4>Section Content</h4><input class="form-control mb-3" name="heading" value="{{ old('heading', $promoGrid->heading) }}"><textarea class="form-control mb-3" name="description" rows="3">{{ old('description', $promoGrid->description) }}</textarea><input class="form-control mb-4" name="heading_link" value="{{ old('heading_link', $promoGrid->heading_link) }}">
<h4>Small Card One</h4><img src="{{ str_starts_with($promoGrid->small_one_image, 'http') ? $promoGrid->small_one_image : asset('storage/' . $promoGrid->small_one_image) }}" width="140" height="100" style="object-fit:cover" class="mb-3"><input type="file" class="form-control mb-3" name="small_one_image"><input class="form-control mb-3" name="small_one_label" value="{{ old('small_one_label', $promoGrid->small_one_label) }}"><input class="form-control mb-4" name="small_one_link" value="{{ old('small_one_link', $promoGrid->small_one_link) }}">
<h4>Small Card Two</h4><img src="{{ str_starts_with($promoGrid->small_two_image, 'http') ? $promoGrid->small_two_image : asset('storage/' . $promoGrid->small_two_image) }}" width="140" height="100" style="object-fit:cover" class="mb-3"><input type="file" class="form-control mb-3" name="small_two_image"><input class="form-control mb-3" name="small_two_label" value="{{ old('small_two_label', $promoGrid->small_two_label) }}"><input class="form-control mb-4" name="small_two_link" value="{{ old('small_two_link', $promoGrid->small_two_link) }}">
<h4>Sale Badge</h4><input class="form-control mb-3" name="sale_percent" value="{{ old('sale_percent', $promoGrid->sale_percent) }}"><input class="form-control mb-4" name="sale_text" value="{{ old('sale_text', $promoGrid->sale_text) }}">
<h4>Status</h4><select class="form-control mb-4" name="status"><option value="1" @selected(old('status', $promoGrid->status) == 1)>Active</option><option value="0" @selected(old('status', $promoGrid->status) == 0)>Inactive</option></select><button type="submit" class="input-group-text mx-auto mb-4">Update Promo Grid</button>
</form></div>@include('admin.footer')</div></div>
