@php $value = fn ($field) => old($field, $product?->{$field}); @endphp
@if($errors->any())<div class="alert alert-danger">@foreach($errors->all() as $error)<div>{{ $error }}</div>@endforeach</div>@endif
<form action="{{ $formAction }}" method="POST" enctype="multipart/form-data" class="main-footer">
    @csrf @if($formMethod !== 'POST') @method($formMethod) @endif
    <h2 class="text-center mb-5">{{ $formTitle }}</h2>
    <h4>Shop Page Settings</h4><input class="form-control mb-3" name="hero_title" placeholder="Shop Standard" value="{{ $value('hero_title') }}"><label class="form-label">Hero Image</label><input type="file" class="form-control mb-3" name="hero_image" accept="image/*">@if($product?->hero_image)<img src="{{ asset('storage/' . $product->hero_image) }}" alt="Hero" width="160" height="100" style="object-fit:cover" class="mb-4">@endif
    <label class="form-label">Categories and counts, separated by |</label><input class="form-control mb-3" name="category_names" placeholder="Dresses|Boots|Coat" value="{{ $value('category_names') }}"><input class="form-control mb-3" name="category_counts" placeholder="10|17|22" value="{{ $value('category_counts') }}"><input class="form-control mb-3" name="colors" placeholder="Black|White|Red" value="{{ $value('colors') }}"><input class="form-control mb-3" name="sizes" placeholder="XS|S|M|L|XL" value="{{ $value('sizes') }}"><input class="form-control mb-4" name="tags" placeholder="Vintage|Cotton|Formal" value="{{ $value('tags') }}">
    @php $productCategories = ['Shirts', 'Shorts', 'T-Shirt', 'Jeans', 'Jackets', 'Dresses', 'Hoodies', 'Sneakers']; $currentCategory = $value('category'); if ($currentCategory && !in_array($currentCategory, $productCategories, true)) $productCategories[] = $currentCategory; @endphp
    <h4>Product</h4><input class="form-control mb-3" name="name" placeholder="Product name" value="{{ $value('name') }}" required><label class="form-label">Product Category</label><select class="form-select mb-3" name="category"><option value="">Select category</option>@foreach($productCategories as $category)<option value="{{ $category }}" {{ $currentCategory === $category ? 'selected' : '' }}>{{ $category }}</option>@endforeach</select><div class="row"><div class="col-md-6"><input class="form-control mb-3" name="price" placeholder="$80" value="{{ $value('price') }}"></div><div class="col-md-6"><input class="form-control mb-3" name="sale_label" placeholder="GET 20% OFF" value="{{ $value('sale_label') }}"></div></div><label class="form-label">Product Image</label><input type="file" class="form-control mb-3" name="image" accept="image/*">@if($product?->image)<img src="{{ asset('storage/' . $product->image) }}" alt="Product" width="160" height="100" style="object-fit:cover" class="mb-4">@endif
    <label class="form-check mb-4"><input class="form-check-input" type="checkbox" name="status" value="1" {{ old('status', $product?->status ?? true) ? 'checked' : '' }}> Active</label><button type="submit" class="btn btn-primary">{{ $product ? 'Update Shop Product' : 'Save Shop Product' }}</button>
</form>