@php $value = fn ($field) => old($field, $project?->{$field}); @endphp
@if($errors->any())<div class="alert alert-danger">@foreach($errors->all() as $error)<div>{{ $error }}</div>@endforeach</div>@endif
<form action="{{ $formAction }}" method="POST" enctype="multipart/form-data" class="main-footer">
    @csrf @if($formMethod !== 'POST') @method($formMethod) @endif
    <h2 class="text-center mb-5">{{ $formTitle }}</h2><h4>Hero</h4><input class="form-control mb-3" name="hero_title" placeholder="Project title" value="{{ $value('hero_title') }}" required><input class="form-control mb-4" name="hero_breadcrumb" placeholder="Portfolio Details 1" value="{{ $value('hero_breadcrumb') }}">
    <div class="row">@foreach(['image_main' => 'Main Image', 'image_two' => 'Gallery Image 2', 'image_three' => 'Gallery Image 3'] as $field => $label)<div class="col-md-4"><label class="form-label">{{ $label }}</label><input type="file" class="form-control mb-3" name="{{ $field }}" accept="image/*">@if($project?->{$field})<img src="{{ asset('storage/' . $project->{$field}) }}" alt="{{ $label }}" width="130" height="90" style="object-fit:cover" class="mb-4">@endif</div>@endforeach</div>
    <h4>Content</h4><input class="form-control mb-3" name="article_title" placeholder="Research & Planning" value="{{ $value('article_title') }}"><textarea class="form-control mb-3" name="article_paragraph_one" rows="4" placeholder="First paragraph">{{ $value('article_paragraph_one') }}</textarea><textarea class="form-control mb-4" name="article_paragraph_two" rows="4" placeholder="Second paragraph">{{ $value('article_paragraph_two') }}</textarea>
    <h4>Project Details</h4><div class="row">@foreach(['client' => 'Client', 'seatpad' => 'Seatpad', 'location' => 'Location', 'shipping' => 'Shipping', 'category' => 'Category'] as $field => $label)<div class="col-md-6"><label class="form-label">{{ $label }}</label><input class="form-control mb-3" name="{{ $field }}" value="{{ $value($field) }}"></div>@endforeach</div>
    <h4>Previous and Next</h4><div class="row"><div class="col-md-4"><input class="form-control mb-3" name="previous_label" placeholder="Previous label" value="{{ $value('previous_label') }}"></div><div class="col-md-4"><input class="form-control mb-3" name="previous_title" placeholder="Previous title" value="{{ $value('previous_title') }}"></div><div class="col-md-4"><input class="form-control mb-3" name="previous_url" placeholder="/portfolio/details-5" value="{{ $value('previous_url') }}"></div></div><div class="row"><div class="col-md-4"><input class="form-control mb-3" name="next_label" placeholder="Next label" value="{{ $value('next_label') }}"></div><div class="col-md-4"><input class="form-control mb-3" name="next_title" placeholder="Next title" value="{{ $value('next_title') }}"></div><div class="col-md-4"><input class="form-control mb-3" name="next_url" placeholder="/portfolio/details-2" value="{{ $value('next_url') }}"></div></div><input class="form-control mb-4" name="related_category" placeholder="SWEATER" value="{{ $value('related_category') }}">
    <label class="form-check mb-4"><input class="form-check-input" type="checkbox" name="status" value="1" {{ old('status', $project?->status ?? true) ? 'checked' : '' }}> Active</label><button type="submit" class="btn btn-primary">{{ $project ? 'Update Portfolio' : 'Save Portfolio' }}</button>
</form>