@include('admin.header')
@include('admin.sidebar')
<div id="layoutSidenav"><div id="layoutSidenav_content"><div class="container-fluid px-4">
@if($errors->any())<div class="alert alert-danger">@foreach($errors->all() as $error)<div>{{ $error }}</div>@endforeach</div>@endif
<form action="{{ route('admin.featured-offers.update', $featuredOffer) }}" class="featured-offers main-footer" method="POST" enctype="multipart/form-data">@csrf @method('PUT')
<h2 class="text-center mb-5">Edit Featured Offer</h2>
<img src="{{ str_starts_with($featuredOffer->image, 'http') ? $featuredOffer->image : asset('storage/' . $featuredOffer->image) }}" width="180" height="120" style="object-fit:cover" class="mb-3"><input type="file" class="form-control mb-4" name="image">
<h4>Section Subtitle</h4><input class="form-control mb-3" name="section_subtitle" value="{{ old('section_subtitle', $featuredOffer->section_subtitle) }}"><h4>Section Title</h4><input class="form-control mb-3" name="section_title" value="{{ old('section_title', $featuredOffer->section_title) }}"><h4>See All</h4><input class="form-control mb-3" name="see_all_text" value="{{ old('see_all_text', $featuredOffer->see_all_text) }}"><input class="form-control mb-4" name="see_all_link" value="{{ old('see_all_link', $featuredOffer->see_all_link) }}"><h4>Offer Tag</h4><input class="form-control mb-3" name="tag" value="{{ old('tag', $featuredOffer->tag) }}" required><h4>Offer Title</h4><input class="form-control mb-3" name="title" value="{{ old('title', $featuredOffer->title) }}" required><h4>Background Style</h4><select class="form-control mb-4" name="background_class"><option value="offer-pink" @selected(old('background_class', $featuredOffer->background_class) === 'offer-pink')>Pink</option><option value="offer-blue" @selected(old('background_class', $featuredOffer->background_class) === 'offer-blue')>Blue</option><option value="offer-light-pink" @selected(old('background_class', $featuredOffer->background_class) === 'offer-light-pink')>Light Pink</option><option value="offer-gray" @selected(old('background_class', $featuredOffer->background_class) === 'offer-gray')>Gray</option></select><h4>Button</h4><input class="form-control mb-3" name="button_text" value="{{ old('button_text', $featuredOffer->button_text) }}"><input class="form-control mb-4" name="button_link" value="{{ old('button_link', $featuredOffer->button_link) }}"><h4>Status</h4><select class="form-control mb-4" name="status"><option value="1" @selected(old('status', $featuredOffer->status) == 1)>Active</option><option value="0" @selected(old('status', $featuredOffer->status) == 0)>Inactive</option></select><button type="submit" class="input-group-text mx-auto mb-4">Update Featured Offer</button>
</form></div>@include('admin.footer')</div></div>
